# Generated by Django 5.1.7 on 2025-03-16 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
    ]
