# Generated by Django 5.1.7 on 2025-03-15 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todomodel',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
